services:
  postgres:
    image: postgres:15
    container_name: ecovolt-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ecovolt
      PGTZ: America/Fortaleza
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: ecovolt-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecovolt
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SERVER_PORT: 8000
      TZ: America/Fortaleza
    ports:
      - "8000:8000"
    restart: on-failure

volumes:
  pgdata: